name: Publish Blog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: textbook/git-checkout-submodule-action@2.1.1
    - uses: peaceiris/actions-hugo@v2.4.6
    - name: Build Hugo Pages
      run: |
        hugo -t even
    - name: Deploy Blog
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.Access_Token }}
        repository: omuumo/omuumo.github.io
        directory: ./public
